kafka:
  producer:
    enable: true
    servers: ${kafka.address:'192.168.68.115:9092'}
    retries: 10
  #  消费端估计都用不上
  consumer:
    enable: true
    enableAutoCommit: true
    groupId: youzan-customized-service-group
    servers: ${kafka.address:'192.168.68.115:9092'}
    loyaltyServers: ${kafka.address:'192.168.68.115:9092'}